# Site settings
title: "k1chuu"
description: "root@kali:~/#"
author: "Kishore"
#email: "your@email.com"

# GitHub Pages theme
theme: minima
markdown: kramdown

# Social profiles
github_username: twh4t

# Optional: pagination
paginate: 5
paginate_path: "/page:num/"
